// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AskQuestion(arg1:string,arg2:number):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function LoginStudent(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function RegisterStudent(arg1:string,arg2:string,arg3:string):Promise<main.LoginResult>;
